# Site settings
title: Cristiano Miranda - Software Engineer
description: A blog about lorem ipsum dolor sit amet
url: "https://cristianomiranda.com"

# User settings
username: Cristiano Miranda
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Engineer
email: me@cristianomiranda.com
twitter_username: dontclickhere_
github_username:  lorem_ipsum
linkedin_username: mirandacristiano

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
